# Generated by Django 3.2.9 on 2021-12-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='website',
            new_name='shortUrl',
        ),
    ]
