# Generated by Django 3.1.1 on 2021-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_rename_website_link_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
